<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
	'MailgunDashboard_Dashboard' => dirname( __FILE__ ) . '/controllers/dashboard.php',
	'MailgunDashboard_Settings' => dirname( __FILE__ ) . '/controllers/settings.php',
	'MailgunDashboard_Admin_Menu' => dirname( __FILE__ ) . '/controllers/admin_menu.php',
	'MailgunDashboard_Main' => dirname( __FILE__ ) . '/controllers/main.php',
);
