<?php
use \Controllers\Mailgun_Dashboard_Settings;
?>

<h1><?php echo __( 'Mailgun&#174; Dashboard Settings', MAILGUN_DASHBOARD_CONTEXT ); ?></h1>

<form method="post" action="options.php">
    <?php echo settings_fields( Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_OPTIONS_GROUP ); ?>
        <table class="form-table">
            <tbody>
                <tr valign="top">
                    <th scope="row"><label for="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_API_KEY_OPTION_NAME; ?>"><?php echo __( 'Mailgun API key', MAILGUN_DASHBOARD_CONTEXT ); ?></label></th>
                    <td><input type="text" id="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_API_KEY_OPTION_NAME; ?>" name="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_API_KEY_OPTION_NAME; ?>" value="<?php echo get_option( Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_API_KEY_OPTION_NAME ); ?>" class="regular-text js-mgd-<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_API_KEY_OPTION_NAME; ?>"/></td>
                </tr>

                <tr valign="top">
                    <th scope="row"><label for="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_DOMAIN_OPTION_NAME; ?>"><?php echo __( 'Mailgun domain', MAILGUN_DASHBOARD_CONTEXT ); ?></label></th>
                    <td><input type="text" id="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_DOMAIN_OPTION_NAME; ?>" name="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_DOMAIN_OPTION_NAME; ?>" value="<?php echo get_option( Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_DOMAIN_OPTION_NAME ); ?>" class="regular-text  js-mgd-<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_DOMAIN_OPTION_NAME; ?>"/></td>
                </tr>
                <?php
                if ( class_exists( 'Mailgun' ) ):
                ?>
                <tr valign="top">
                    <th scope="row"><label for="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_SETTINGS_SOURCE_NAME; ?>"><?php echo __( 'Use the settings from Mailgun&#174; plugin', MAILGUN_DASHBOARD_CONTEXT ); ?></label></th>
                    <td><input type="checkbox" id="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_SETTINGS_SOURCE_NAME; ?>" name="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_SETTINGS_SOURCE_NAME; ?>" value="1" <?php echo '1' === get_option( Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_SETTINGS_SOURCE_NAME ) ? 'checked' : ''  ?> class="js-mgd-mailgun_settings_source"></td>
                </tr>
                <?php
                endif;
                ?>
            </tbody>
        </table>
		<?php  submit_button(); ?>
</form>
