<?php
use \Controllers\Mailgun_Dashboard_Settings;
?>

<h1><?php echo __( 'Mailgun&#174; Dashboard Settings', MAILGUN_DASHBOARD_CONTEXT ); ?></h1>

<form method="post" action="options.php">
    <?php echo settings_fields( Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_OPTIONS_GROUP ); ?>
        <table class="form-table">
            <tbody>
                <tr valign="top">
                    <th scope="row"><label for="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_API_KEY_OPTION_NAME; ?>">Mailgun API key</label></th>
                    <td><input type="text" id="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_API_KEY_OPTION_NAME; ?>" name="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_API_KEY_OPTION_NAME; ?>" value="<?php echo get_option( Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_API_KEY_OPTION_NAME ); ?>" class="regular-text"/></td>
                </tr>

                <tr valign="top">
                    <th scope="row"><label for="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_DOMAIN_OPTION_NAME; ?>">Mailgun domain</label></th>
                    <td><input type="text" id="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_DOMAIN_OPTION_NAME; ?>" name="<?php echo Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_DOMAIN_OPTION_NAME; ?>" value="<?php echo get_option( Mailgun_Dashboard_Settings::MAILGUN_DASHBOARD_DOMAIN_OPTION_NAME ); ?>" class="regular-text"/></td>
                </tr>
            </tbody>
        </table>
		<?php  submit_button(); ?>
</form>
